# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Software\Steam\steamapps\common\Backpack Battles\lienup simulator\lineup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPoint
from PyQt5.QtWidgets import (
    QTableWidget,
    QTableWidgetItem,
    QListWidget,
    QListWidgetItem,
    QLabel,
    QHBoxLayout,
    QVBoxLayout,
)
from PyQt5.QtGui import QPixmap
from pathlib import Path
from widget_utils import ItemList, BagList


class LineUpSimulator(QMainWindow):
    def __init__(self, path: str = None, icon_size: list = [50, 50], **kwargs) -> None:
        super().__init__()
        self.path = "./assets/"
        self.img_list = sorted(Path(path).glob("*.png"))
        self.h = 1000
        self.w = 1000
        self.setObjectName("MainWindow")
        self.setMouseTracking(True)
        self.resize(self.w, self.h)
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")

        layout = QHBoxLayout()
        self.centralwidget.setLayout(layout)

        self.setCentralWidget(self.centralwidget)

        # * create Item Qlist
        self.item_list = ItemList(path=path, icon_size=icon_size)

        # * create Bag Qlist
        self.bag_list = BagList()

        # * add layout
        left_layout = QVBoxLayout()
        right_layout = QVBoxLayout()
        left_layout.addWidget(self.item_list)
        right_layout.addWidget(self.bag_list)
        layout.addLayout(left_layout, 40)
        layout.addLayout(right_layout, 60)


path = "./assets"


if __name__ == "__main__":
    app = QApplication(sys.argv)
    myWin = LineUpSimulator(path=path, icon_size=[60, 60])
    myWin.setMouseTracking(True)
    myWin.show()
    sys.exit(app.exec_())
